name: Deploy Falcon to Google Cloud

env:
    SERVICE_NAME: 'github_deploy_falcon'
    GCP_PROJECT_ID: 'infinite-glow-462417-u6'
    DOCKER_IMAGE_URL: us-central1-docker.pkg.dev/aw_demo/falcon_demo/falcon_demo

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Google Cloud CLI
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: '${{ secrets.GCP_SA_KEY }}'
                  project_id: ${{env.GCP_PROJECT_ID}}

            - name: Set up Cloud SDK
              uses: 'google-github-actions/setup-gcloud@v2'

            - name: Configure Docker
              run: |
                  gcloud auth configure-docker us-central1-docker.pkg.dev

            - name: Build and Push Docker Image
              run: |
                  docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest -f './Dockerfile' .
                  docker push ${{ env.DOCKER_IMAGE_URL }}:latest

            - name: Deploy to Cloud Run
              run: |
                  echo SERVICE_NAME $SERVICE_NAME
                  gcloud run deploy $SERVICE_NAME \
                  --image ${{ env.DOCKER_IMAGE_URL }}:latest \
                  --platform managed \
                  --allow-unauthenticated
