name: Deploy Falcon to Google Cloud

env:
    SERVICE_NAME: 'github_deploy_falcon'
    GCP_PROJECT_ID: 'infinite-glow-462417-u6'

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Google Cloud CLI
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: '${{ secrets.GCP_SA_KEY }}'
                  project_id: ${{env.GCP_PROJECT_ID}}

            - name: Build Docker image
              run: |
                  docker image build --file './Dockerfile' --tag 'quote:latest' .

            - name: Push Docker image to Google Container Registry
              run: |
                  docker push gcr.io/${{env.GCP_PROJECT_ID}}/quote:latest
                  echo "DOCKER_IMAGE_URL=gcr.io/${{env.GCP_PROJECT_ID}}/quote:latest"

            - name: Deploy to Cloud Run
              run: |
                  echo SERVICE_NAME $SERVICE_NAME
                  gcloud run deploy $SERVICE_NAME \
                  --image gcr.io/${{env.GCP_PROJECT_ID}}/quote:latest \
                  --platform managed \
                  --allow-unauthenticated
